name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Gradle wrapper
        run: gradle wrapper --gradle-version 8.13 --distribution-type bin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Assemble Debug build
        run: ./gradlew assembleDebug
