name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Prepare Gradle Wrapper (no binaries in repo)
        run: bash scripts/prepare-wrapper.sh

      - name: Build Debug Kotlin
        run: ./gradlew :app:compileDebugKotlin --no-daemon
